#!/bin/sh
# Generated by `aval hook install`. Do not edit — regeneration overwrites it.
#
# Prints the current decision heads at session start, so whatever is about to
# write code starts from what was decided rather than from what it can infer.
#
# Repo-specific caveats belong in .claude/aval-hook.local.md, which this
# appends and which `aval hook install` never touches.

notes=".claude/aval-hook.local.md"

# No aval, no output, no failure. A session must not depend on a tool the
# person who started it has not installed.
command -v aval >/dev/null 2>&1 || exit 0

# Silent when there is nothing to say: no registry here, or a corpus that does
# not resolve. `heads` renders nothing rather than a partial projection, and
# reporting a broken corpus is the gate's job, not this one's.
heads=$(aval heads 2>/dev/null) || exit 0
[ -n "$heads" ] || exit 0

cat <<'PREAMBLE'
ARCHITECTURE DECISIONS — these are decided. Do not re-litigate them, and do
not restate them in another file; that is the duplication this corpus exists
to end.

  aval resolve <key> [--scope S]   what is decided, with an exit code
  aval show <record>               one record, and whether it still holds
  aval history <key>               how it got here — history, not authority

To change one, write a record that `replaces` it. Editing the old record is
not how supersession works here, and `aval check` will say so.

What is deployed is not what was decided. Two implementations both running is
not evidence that both were chosen — it is equally consistent with one having
replaced the other and the code not having caught up. Ask someone; do not
infer a decision from what is running.
PREAMBLE

echo
printf '%s\n' "$heads"

if [ -s "$notes" ]; then
  echo
  cat "$notes"
fi
