#!/bin/sh
# Duro design-system session bootstrap — GENERATED by `duro hook install`.
# Regenerate: npx -y @duro-app/cli hook install   (--check verifies it in CI)
#
# Injects the consult-first preamble plus the component catalog into agent
# context at SessionStart, so "check the design system before building UI" is
# ambient context instead of a step an agent has to remember. Then runs
# `duro doctor`, which says nothing unless this repo's build wiring flattens
# the components' styles.
#
# Do not hand-edit. Repo-specific caveats go in
# .claude/duro-hook.local.md — appended below, and left alone by regeneration.
cache=".claude/.duro-session.cache"
notes=".claude/duro-hook.local.md"
doctor=".claude/.duro-session.cache.doctor"
pin="#duro-hook-pin 5.0.0"

# npx resolution dominates session start; the catalog only changes on upgrade.
# Refetch when it is missing, a week old, fetched with another floor (its
# first line), or older than this script (a regenerate).
if [ ! -s "$cache" ] || [ "$(head -n 1 "$cache" 2>/dev/null)" != "$pin" ] ||
  [ -n "$(find "$cache" -mtime +7 2>/dev/null)" ] || [ ".claude/hooks/duro-catalog.sh" -nt "$cache" ]; then
  # The pin is written with the payload, so a failed fetch (or one that
  # printed nothing) leaves the old cache as it was and never a pin-only file.
  if { echo "$pin"; npx -y @duro-app/cli@^5.0.0 hook session-start; } >"$cache.tmp" 2>/dev/null &&
    [ -n "$(tail -n +2 "$cache.tmp")" ]; then
    mv "$cache.tmp" "$cache"
  else
    rm -f "$cache.tmp"
    if [ -s "$cache" ] && [ "$(head -n 1 "$cache")" != "$pin" ]; then
      echo "duro: the catalog below is from an older CLI and could not be refreshed; run: npx -y @duro-app/cli@^5.0.0 hook install" >&2
    fi
  fi
fi

# Offline with no cache yet: stay silent rather than fail the session.
if [ -s "$cache" ]; then
  # The pin line is bookkeeping, not catalog: skip it, and only it.
  case "$(head -n 1 "$cache")" in
    '#duro-hook-pin '*) tail -n +2 "$cache" ;;
    *) cat "$cache" ;;
  esac
  if [ -s "$notes" ]; then
    echo
    cat "$notes"
  fi
fi

# duro doctor reads build config, entries and stylesheets. Re-run it when one
# of those changes rather than on a timer, so an edit shows up next session
# and a healthy repo only pays for npx after touching its config.
key=$(find . -maxdepth 4 \( -name node_modules -o -name .git -o -name dist -o -name build \) -prune -o \
  -type f \( -name package.json -o -name pnpm-workspace.yaml -o -name '*.css' -o -name 'vite*' \
  -o -name 'babel*' -o -name '.babelrc*' -o -name '*.babel.*' -o -name 'postcss*' \
  -o -name 'root.tsx' -o -name 'main.tsx' -o -name 'index.tsx' \) -exec cksum {} + 2>/dev/null |
  sort | cksum)
# The floor is part of the key: a new floor reruns the doctor.
key="5.0.0 $key"
if [ "$key" != "$(cat "$doctor.key" 2>/dev/null)" ]; then
  if npx -y @duro-app/cli@^5.0.0 doctor --session >"$doctor.tmp" 2>/dev/null; then
    mv "$doctor.tmp" "$doctor"
    echo "$key" >"$doctor.key"
  else
    rm -f "$doctor.tmp"
  fi
fi
if [ -s "$doctor" ]; then
  echo
  cat "$doctor"
fi
