#!/bin/sh
# Duro plan-mode nudge — GENERATED by `duro hook install`.
# Regenerate: npx -y @duro-app/cli hook install   (--check verifies it in CI)
#
# Claude Code runs this on every UserPromptSubmit with the event as JSON on
# stdin. In plan mode it prints a short nudge toward fresh mockup directions
# (handoff.fresh-directions-trigger); otherwise, or on input it cannot read,
# it prints nothing. Always exits 0: it must never fail the prompt.
#
# Do not hand-edit.
{ payload=$(cat); } 2>/dev/null || exit 0
if printf '%s\n' "$payload" |
  grep -Eq '"permission_mode"[[:space:]]*:[[:space:]]*"plan"' 2>/dev/null; then
  cat <<'NUDGE'
Planning in a Duro consumer. If this plan adds a new screen, or makes a material choice in
layout, hierarchy or interaction (handoff.fresh-directions-trigger), its first 🧑 decision is
picking a direction: load the duro-mockup skill now (duro skill install if this repo lacks it)
and draw 2–4 directions with `duro mockup` before ExitPlanMode. A fix that restores an existing
design reuses the picked artboard instead; any other UI change needs no mockup.
NUDGE
fi
exit 0
