#!/bin/sh
# Duro design-system session bootstrap — GENERATED by `duro hook install`.
# Regenerate: npx -y @duro-app/cli hook install   (--check verifies it in CI)
#
# Injects the consult-first preamble plus the component catalog into agent
# context at SessionStart, so "check the design system before building UI" is
# ambient context instead of a step an agent has to remember.
#
# Do not hand-edit. Repo-specific caveats go in
# .claude/duro-hook.local.md — appended below, and left alone by regeneration.
cache=".claude/.duro-session.cache"
notes=".claude/duro-hook.local.md"

# npx resolution dominates session start; the catalog only changes on upgrade.
if [ ! -s "$cache" ] || [ -n "$(find "$cache" -mtime +7 2>/dev/null)" ]; then
  if npx -y @duro-app/cli@^1.2.0 hook session-start >"$cache.tmp" 2>/dev/null; then
    mv "$cache.tmp" "$cache"
  else
    rm -f "$cache.tmp"
  fi
fi

# Offline with no cache yet: stay silent rather than fail the session.
[ -s "$cache" ] || exit 0
cat "$cache"

if [ -s "$notes" ]; then
  echo
  cat "$notes"
fi
