import { type RouteConfig, index, layout, route } from "@react-router/dev/routes"

export default [
  layout("routes/dashboard.tsx", [
    index("routes/home.tsx"),
    route("settings", "routes/settings.tsx"),
    route("admin", "routes/admin.tsx", [
      index("routes/admin.invites.tsx"),
      route("users", "routes/admin.users.tsx"),
      route("applications", "routes/admin.applications.tsx"),
      route("applications/:id", "routes/admin.applications.$id.tsx"),
      route("principals", "routes/admin.principals.tsx"),
      route("principals/:id", "routes/admin.principals.$id.tsx"),
      route("grants", "routes/admin.grants.tsx"),
      route("group-mappings", "routes/admin.group-mappings.tsx"),
      route("access-requests", "routes/admin.access-requests.tsx"),
      route("access-requests/:id", "routes/admin.access-requests.$id.tsx"),
      route("invitations", "routes/admin.invitations.tsx"),
      route("audit", "routes/admin.audit.tsx"),
      route("authz-playground", "routes/admin.authz-playground.tsx"),
      route("plugins", "routes/admin.plugins.tsx"),
      route("plugins/:slug", "routes/admin.plugins.$slug.tsx"),
    ]),
  ]),
  route("auth/callback", "routes/auth.callback.tsx"),
  route("auth/logout", "routes/auth.logout.ts"),
  route("health", "routes/health.ts"),
  route("invite/:token", "routes/invite.tsx"),
  route("invite/:token/create-account", "routes/invite-create-account.tsx"),
  route("reinvite/:token", "routes/reinvite.tsx"),
  route("welcome", "routes/welcome.tsx"),
  route("api/bootstrap-invite", "routes/api.bootstrap-invite.ts"),
  route("api/authz/check", "routes/api.authz.check.ts"),
  route("api/authz/check-bulk", "routes/api.authz.check-bulk.ts"),
  route("api/principals/:id/grants", "routes/api.principals.$id.grants.ts"),
  route("api/access-requests", "routes/api.access-requests.ts"),
  route("api/invitations", "routes/api.invitations.ts"),
] satisfies RouteConfig
